### ISSUE TITLE
prepdata appears to be missing

### ISSUE THREAD

**Issue by ghost** [erdc/cmtb#2]
Attempting **RunWorkFlow_CSHORE.py**

I installed matplotlib and scipy, then tried to run the file and got this error.

```
(venv) PS D:\cmtb> python2 RunWorkFlow_CSHORE.py
Traceback (most recent call last):
  File "RunWorkFlow_CSHORE.py", line 9, in <module>
    from frontback.frontBackCSHORE import CSHORE_analysis, CSHOREsimSetup
  File "D:\cmtb\frontback\frontBackCSHORE.py", line 3, in <module>
    from prepdata import inputOutput, prepDataLib
ImportError: No module named prepdata
```

It looks like there should be a submodule for this project, called "prepdata," but when I tried to access the [link](https://github.com/erdc/prepdata/tree/b737a2968e8118e8a25f03411d1401cd106f2d64) I get a 404.

How can I access this submodule?

Thanks in advance

**Comment by SBFRF** [comment]
hi @friend-code the submodule currently is available for collaborators only.  What are you doing with the project?  how'd you hear about this?  Are you interested in working on the project?

**Comment by ghost** [comment]
Hello @SBFRF, thanks for the quick reply.

I was directed to this project by my mentors for my capstone project. I'm studying Environmental Engineering at the University of Minnesota. I was told that I might be able to use this code to perform wind-wave analysis on some shoreline profiles I was given.

**Comment by SBFRF** [comment]
interesting, i can share the code with you, but we're going through a bit of a refactor right now. @thesser1 what do you think would be the best path forward?

**Comment by SBFRF** [comment]
@friend-code  are you looking to generate waves from wind or using waves in the windsea band to understand the shoreline profile change??

**Comment by ghost** [comment]
@SBFRF the latter.

**Comment by SBFRF** [comment]
@friend-code  are you looking to utilize your own profiles, or profiles at the ERDC field research facility in Duck, NC?

**Comment by ghost** [comment]
@SBFRF I would like to analyze [my own profiles](https://docs.google.com/spreadsheets/d/1jRL0NVI7grE88p7I7btmNqcm9uugiXoIrXyuLtrmz18/edit?usp=sharing), which you can view here if you'd like.

**Comment by SBFRF** [comment]
@friend-code i don't think that the cmtb is the framework your're looking for.  It's developed (to this point) to interface data from the Field Research Facility in Duck NC to various coastal models.  You are probably better off just using the CSHORE model directly.  https://github.com/erdc/cshore  If you have questions/problems please tag me over there, and we'll make sure you get what you need.
